# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ny-handr <ny-handr@student.42antananari    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/01/29 08:16:58 by ny-handr          #+#    #+#              #
#    Updated: 2026/03/11 11:40:30 by todina-r         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC=cc

CFLAGS=-Wall -Wextra -Werror

NAME=libft.a

SRCS=	ft_atoi.c\
		ft_bzero.c\
		ft_calloc.c\
		ft_isalnum.c\
		ft_isalpha.c\
		ft_isascii.c\
		ft_isdigit.c\
		ft_isprint.c\
		ft_memchr.c\
		ft_memcmp.c\
		ft_memcpy.c\
		ft_memmove.c\
		ft_memset.c\
		ft_split.c\
		ft_strchr.c\
		ft_strdup.c\
		ft_strjoin.c\
		ft_strlcat.c\
		ft_strlcpy.c\
		ft_strlen.c\
		ft_strncmp.c\
		ft_strnstr.c\
		ft_strrchr.c\
		ft_strtrim.c\
		ft_substr.c\
		ft_tolower.c\
		ft_toupper.c\
		ft_itoa.c\
		ft_strmapi.c\
		ft_striteri.c\
		ft_putchar_fd.c\
		ft_putstr_fd.c\
		ft_putendl_fd.c\
		ft_putnbr_fd.c\
		ft_lstnew.c\
		ft_lstadd_front.c\
		ft_lstsize.c\
		ft_lstlast.c\
		ft_lstadd_back.c\
		ft_lstdelone.c\
		ft_lstclear.c\
		ft_lstiter.c\
		ft_lstmap.c\
		gnl/gnl.c\

OBJS=$(SRCS:.c=.o)

AR=ar rcs

RM=rm -f

all: $(NAME)

$(NAME): $(OBJS)
	$(MAKE) -C ./printf/ all
	cp printf/libftprintf.a $(NAME)
	$(AR) $@ $^

%.o : %.c
	$(CC) $(CFLAGS) -c $^ -o $@ -I.

clean:
	$(MAKE) -C ./printf/ clean
	$(RM) $(OBJS)

fclean: clean
	$(MAKE) -C ./printf/ fclean
	$(RM) $(NAME)

re: fclean all
